defaults:
  - dataset: clip1
  - model: scow
  - override hydra/job_logging: none
  - override hydra/hydra_logging: none
  - _self_

exp_name: ???
seed: 42
device: cuda  # set to cpu to force CPU
mode: train  # train or infer
debug: false
progress: false

scratch_dir: data/scratch
save_dir: ${scratch_dir}/experiments/${exp_name}

datasets: clip1

data:
  csv_path: ${dataset.feature_csv}
  feature_cols:
    - n_words
    - tiny
    - tiny.en
    - base
    - base.en
    - small
    - small.en
    - medium
    - medium.en
    - large
    - large-v2
    - large-v3
    - large-v3-turbo
    # - stoi
    # - estoi
    # - pesq
    # - dns_sig
    # - dns_bak
    # - dns_ovrl

train:
  batch_size: 256
  epochs: 50
  lr: 1e-4
  optim: adamw
  corr_lambda: 0.4
  val_split: 0.2

infer:
  ckpt_dataset: ${dataset.name}
  splits:
    - valid
    - eval
  clamp_scores: true
  scale_to_percentage: true
  output_name: ${dataset.name}_{split}_ckpt${infer.ckpt_dataset}.csv

hydra:
  run:
    dir: .
  output_subdir: null
  sweep:
    dir: .
    subdir: sweep
  job:
    chdir: false
